pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/MaliViaux/autofixapp']])
                dir("AutoFix"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("AutoFix"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t maliviaux/autofix-frontend ."
                            bat "docker push maliviaux/autofix-frontend"
                        }
                    }                    
                }
            }
        }
    }
}